services:
  frontend:
    image: frontend
    build:
      context: client/
      dockerfile: Dockerfile
    networks:
      - mynetwork
    ports:
      - "4200:4200"

  backend:
    image: backend
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
